resnet_parameters = [
    {
        "name": "resnet_conv1",
        "channels": 3,
        "kernel_size": "[7, 7]",
        "padding": "[3, 3]",
        "strides": "[2, 2]",
        "output_shape": [1, 64, 112, 112],
        "input_shape": [1, 3, 224, 224],
        "batch_size": 4,
    },
    {
        "name": "resnet_conv2_2",
        "channels": 64,
        "kernel_size": "[3, 3]",
        "padding": "[1, 1]",
        "strides": "[1, 1]",
        "output_shape": [1, 64, 56, 56],
        "input_shape": [1, 64, 56, 56],
        "batch_size": 4,
    },
    {
        "name": "resnet_conv3_2",
        "channels": 128,
        "kernel_size": "[3, 3]",
        "padding": "[1, 1]",
        "strides": "[1, 1]",
        "output_shape": [1, 128, 28, 28],
        "input_shape": [1, 128, 28, 28],
        "batch_size": 4,
    },
    {
        "name": "resnet_conv4_2",
        "channels": 256,
        "kernel_size": "[3, 3]",
        "padding": "[1, 1]",
        "strides": "[1, 1]",
        "output_shape": [1, 256, 14, 14],
        "input_shape": [1, 256, 14, 14],
        "batch_size": 4,
    },
    {
        "name": "resnet_conv5_1",
        "channels": 256,
        "kernel_size": "[3, 3]",
        "padding": "[1, 1]",
        "strides": "[2, 2]",
        "output_shape": [1, 512, 7, 7],
        "input_shape": [1, 256, 14, 14],
        "batch_size": 4,
    },
    {
        "name": "resnet_conv5_2",
        "channels": 512,
        "kernel_size": "[3, 3]",
        "padding": "[1, 1]",
        "strides": "[1, 1]",
        "output_shape": [1, 512, 7, 7],
        "input_shape": [1, 512, 7, 7],
        "batch_size": 4,
    }
]
